services:
  frontend:
    image: piperr-frontend
    container_name: piperr-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    develop:
      watch:
        - action: sync
          path: frontend/app
          target: /app/app
        - action: sync
          path: frontend/public
          target: /app/public
  server:
    build:
      context: server
      dockerfile: Dockerfile
    image: piperr-server
    container_name: piperr-server
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: server