services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    image: piperr-server
    container_name: piperr-server
    stop_signal: SIGINT
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: rebuild
          path: server