services:
  frontend:
    image: seppaleinen/piperr-frontend
    container_name: piperr-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3004:80"
    develop:
      watch:
        - action: sync
          path: frontend/app
          target: /app/app
        - action: sync
          path: frontend/public
          target: /app/public
  server:
    build:
      context: server
      dockerfile: Dockerfile
    image: seppaleinen/piperr-server
    container_name: piperr-server
    stop_signal: SIGINT
    privileged: true
    volumes:
      - /:/host
      - piperr-data:/install/
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: server

  agent:
    build:
      context: server
      dockerfile: agent.Dockerfile
    image: seppaleinen/piperr-agent
    container_name: piperr-agent
    stop_signal: SIGINT
    privileged: true
    volumes:
      - /:/host
    ports:
      - "8000:8002"
    develop:
      watch:
        - action: rebuild
          path: server

volumes:
  piperr-data:
    name: piperr-data
